version: '3'
services:
  phpmyadmin:
    restart: always
    image: phpmyadmin
    networks:
      - wp-net
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: "${PMA_ARBITRARY}"
      
  dbserver-wordpress:
    restart: always
    hostname: dbserver-wordpress
    image: mysql:5.7
    networks:
      - wp-net
    ports:
      - 3306:3306
    logging:
      driver: "gcplogs"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "${MYSQL_RANDOM_ROOT_PASSWORD}"
    volumes:
      - "/data:/var/lib/mysql"

networks:
  wp-net:
    external: true
